// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2;

namespace Parcial2.Migrations
{
    [DbContext(typeof(SaveContext))]
    [Migration("20210528082937_change01")]
    partial class change01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Parcial2.Model.Reservation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("dateTime")
                        .HasColumnType("int");

                    b.Property<string>("speciality")
                        .HasColumnType("text");

                    b.Property<int>("user")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Parcial2.Model.Speciality", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("especiality")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("Parcial2.Model.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("answer")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Parcial2.Model.securityQuestion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<string>("questions")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("Userid");

                    b.ToTable("SecurityQuestions");
                });

            modelBuilder.Entity("Parcial2.Model.securityQuestion", b =>
                {
                    b.HasOne("Parcial2.Model.User", null)
                        .WithMany("questions")
                        .HasForeignKey("Userid");
                });

            modelBuilder.Entity("Parcial2.Model.User", b =>
                {
                    b.Navigation("questions");
                });
#pragma warning restore 612, 618
        }
    }
}
